import { execSync } from "child_process";

async function createPullRequest() {
  try {
    console.log("=======================================");
    console.log("Creating Pull Request...");
    console.log("=======================================");

    const branchName = `ai-fix-${Date.now()}`;

    console.log(`Creating branch: ${branchName}`);

    execSync(`git checkout -b ${branchName}`, {
      stdio: "inherit",
    });

    execSync(`git config user.name "github-actions[bot]"`);
    execSync(
      `git config user.email "41898282+github-actions[bot]@users.noreply.github.com"`
    );

    execSync(`git add tests pages`, {
      stdio: "inherit",
    });

    const changedFiles = execSync(`git diff --cached --name-only`)
      .toString()
      .trim();

    if (!changedFiles) {
      console.log("No changes detected. Skipping PR creation.");
      process.exit(0);
    }

    console.log("Changed files:");
    console.log(changedFiles);

    execSync(
      `git commit -m "fix: AI self-healing Playwright fixes"`,
      {
        stdio: "inherit",
      }
    );

    execSync(`git push origin ${branchName}`, {
      stdio: "inherit",
    });

    const repo = process.env.GITHUB_REPOSITORY;

    if (!repo) {
      throw new Error("GITHUB_REPOSITORY env variable missing");
    }

    const token = process.env.GITHUB_TOKEN;

    if (!token) {
      throw new Error("GITHUB_TOKEN env variable missing");
    }

    const [owner, repoName] = repo.split("/");

    const response = await fetch(
      `https://api.github.com/repos/${owner}/${repoName}/pulls`,
      {
        method: "POST",

        headers: {
          Authorization: `Bearer ${token}`,
          Accept: "application/vnd.github+json",
          "Content-Type": "application/json",
        },

        body: JSON.stringify({
          title: "AI Self-Healing Playwright Fix",
          head: branchName,
          base: "main",
          body: `
## AI Self-Healing Fix

This PR was automatically generated by the Playwright AI healing pipeline.

### Included
- Playwright test fixes
- Page object fixes
- Selector healing
- Validation rerun

Generated via GitHub Actions + OpenAI + MCP.
          `,
        }),
      }
    );

    if (!response.ok) {
      const errorText = await response.text();

      console.error(errorText);

      throw new Error("Failed to create PR");
    }

    const data = await response.json();

    console.log("Pull Request created successfully");
    console.log(data.html_url);
  } catch (error) {
    console.error("Create PR failed");

    console.error(error);

    process.exit(1);
  }
}

createPullRequest();